const CODE_FIELDS = new Set([
  'code',
  'abap_code',
  'original_code',
  'suggested_code',
  'fix_code',
  'code_skeleton',
  'skeleton',
  'snippet',
  'script',
  'payload'
])
export function isSourceCodeField(key: string): boolean {
  return CODE_FIELDS.has(key.toLowerCase())
}

export const TECHNICAL_LABELS: Record<string, string> = {
  summary: 'Resumo',
  risk_level: 'Risco geral',
  files_analyzed: 'Arquivos analisados',
  findings: 'Achados da revisão',
  severity: 'Gravidade',
  category: 'Categoria',
  file: 'Arquivo',
  line_start: 'Linha inicial',
  line_end: 'Linha final',
  line_hint: 'Localização',
  title: 'Título',
  description: 'Descrição',
  impact: 'Impacto',
  evidence: 'Evidência',
  confidence: 'Confiança',
  original_code: 'Código original',
  suggested_code: 'Código sugerido',
  fix_code: 'Correção sugerida',
  fix_description: 'Orientação da correção',
  validation: 'Como validar',
  approved_patterns: 'Padrões adequados',
  statistics: 'Resumo dos achados',
  total_findings: 'Total',
  critical: 'Críticos',
  high: 'Altos',
  medium: 'Médios',
  low: 'Baixos',
  info: 'Informativos',
  verdict: 'Parecer',
  notes: 'Observações',
  recommendations: 'Opções de enhancement',
  rank: 'Ordem',
  type: 'Tipo',
  name: 'Nome',
  interface_method: 'Interface / método',
  when_called: 'Quando é chamado',
  s4hana_compatible: 'Compatível com S/4HANA',
  compatibility_note: 'Release e compatibilidade',
  pros: 'Vantagens',
  cons: 'Limitações',
  code_skeleton: 'Esqueleto de implementação',
  transaction: 'Transação',
  prerequisites: 'Pré-requisitos',
  additional_notes: 'Observações adicionais',
  score: 'Nota da análise estática',
  score_basis: 'Critérios e limitações da nota',
  issues: 'Pontos de performance',
  measurement_status: 'Medição',
  measurement: 'Evidência de medição',
  general_recommendations: 'Recomendações gerais'
}
export const TECHNICAL_VALUES: Record<string, string> = {
  low: 'Baixa',
  medium: 'Média',
  high: 'Alta',
  critical: 'Crítica',
  info: 'Informativa',
  approved: 'Aprovado',
  approved_with_changes: 'Aprovado com ajustes',
  rejected: 'Requer correção',
  a_confirmar: 'A confirmar',
  confirmed: 'Confirmado',
  hypothesis: 'Hipótese',
  measured: 'Medido',
  not_measured: 'Não medido',
  performance: 'Performance',
  bug: 'Defeito',
  security: 'Segurança',
  style: 'Estilo',
  dead_code: 'Código sem uso',
  deadlock: 'Bloqueio',
  data_loss: 'Perda de dados'
}
